# WARNING
# EDITING THIS FILE MAY MAKE SYNCORD UNABLE TO READ SOME FILES 

CONFIG_PATH="./src/config.json"
CACHE_PATH="./tmp/"
TABLE_INFOS_PATH="./tableinfos.json"
UPSTREAM_FILE_SIZE=24.99 # MiB
COMPRESSIBILITY_FACTOR_SKIP=0.000001
COMPRESSIBILITY_FACTOR_TOLERANCE=0.1
COMPRESSION_CHUNK_SIZE=1024**2